# Generated by Django 2.1.3 on 2018-11-25 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('G', '✓ good'), ('E', '× error'), ('R', '~ running')], default='G', max_length=1)),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('comments', models.IntegerField(blank=True, null=True)),
                ('comments_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('score', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('story_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('N', 'New'), ('O', 'Ok'), ('E', 'Error')], default='N', max_length=1)),
                ('top_ten', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('category', models.CharField(blank=True, default='default', max_length=255)),
            ],
            options={
                'verbose_name': 'story',
                'verbose_name_plural': 'stories',
                'ordering': ('-score', '-story_date'),
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('story_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topper.Story')),
                ('duration', models.IntegerField(default=0)),
                ('podcastId', models.CharField(max_length=200)),
            ],
            bases=('topper.story',),
        ),
        migrations.AddField(
            model_name='story',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='topper.Service'),
        ),
        migrations.AlterUniqueTogether(
            name='story',
            unique_together={('service', 'code', 'date')},
        ),
    ]
