version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    hostname: postgres
    ports:
      - 5432:5432
  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - 6379:6379
  celery:
    container_name: celery
    build:
      context: ./backend/topper
    env_file: .env
    command: celery -A topper beat -l info
    volumes:
      - ./backend/topper:/backend/topper
    depends_on:
      - backend
      - redis
  frontend:
    container_name: frontend
    build:
      context: ./frontend/topper
      dockerfile: Dockerfile
    hostname: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/topper:/frontend/topper
    stdin_open: true
    tty: true
  backend:
    container_name: backend
    build:
      context: ./backend/topper
      dockerfile: Dockerfile
    hostname: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/topper:/backend/topper
      - /backend/topper/node_modules
    depends_on:
      - postgres
    environment:
      WAIT_HOSTS: postgres:5432
    env_file: .env
    stdin_open: true
    tty: true
