version: "3"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    hostname: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/srv/project
    depends_on:
      - postgres
    env_file: .env
    command: >
      bash -c '
      python topper/manage.py makemigrations &&
      python topper/manage.py migrate
      python topper/manage.py runserver'
  postgres:
    container_name: postgres
    image: postgres:latest
    hostname: postgres
    ports:
      - 5432:5432
  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - 6379:6379
  celery:
    container_name: celery
    build:
      context: ./backend
    env_file: .env
    command: celery -A topper worker -l info
    volumes:
      - ./backend:/srv/project
    depends_on:
      - backend
      - redis