# Generated by Django 2.1.3 on 2018-11-13 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('name',), 'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
    ]
