# Generated by Django 2.1.3 on 2018-11-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_date',
            field=models.DateTimeField(null=True),
        ),
    ]
