# Generated by Django 2.1.3 on 2018-11-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='comments',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
