# Generated by Django 2.1.3 on 2018-11-16 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_story_story_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubredditStory',
            fields=[
                ('story_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Story')),
                ('subreddit', models.CharField(max_length=255)),
            ],
            bases=('api.story',),
        ),
    ]
