# Generated by Django 2.1.3 on 2018-11-16 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subredditstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('story_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Story')),
                ('duration', models.IntegerField()),
                ('podcastId', models.CharField(max_length=200)),
            ],
            bases=('api.story',),
        ),
    ]
