# Generated by Django 2.1.3 on 2018-11-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_podcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
